### ISSUE TITLE
Is IngestResponse.requestId always null?

### ISSUE THREAD

**Issue by ml10** [snowflakedb/snowflake-ingest-java#11]
After making an `ingestFiles` request, the `requestId` of `IngestResponse` always appears `null`.

This means that if you call `getRequestUUID()`, it results in an NPE because `java.util.UUID.fromString` will throw on null input.

Here's how I ran across this in my code, trying to get the `requestUUID` out from the `response`. 
```
      }.flatMap{ (response: IngestResponse) =>
        println(s"ingestFiles response: $response")
        val optResponse = Option(response)
        println(s"optResponse: $optResponse")
        optResponse.map(_.getRequestUUID)
      }
```

Sorry this is not java code, but hopefully the intent is clear. Here's the result of a run:

```
[run-main-0] INFO net.snowflake.ingest.SimpleIngestManager - Attempting to unmarshall insert response - HttpResponseProxy{HTTP/1.1 200 OK [Content-Type: application/json, Date: Fri, 19 Jan 2018 22:58:35 GMT, Server: nginx, Strict-Transport-Security: max-age=31536000, X-Frame-Options: deny, Content-Length: 88, Connection: keep-alive] ResponseEntityProxy{[Content-Type: application/json,Content-Length: 88,Chunked: false]}}
ingestFiles response: null
optResponse: Some(null)
java.lang.NullPointerException
  at java.util.UUID.fromString(UUID.java:192)
  at net.snowflake.ingest.connection.IngestResponse.getRequestUUID(IngestResponse.java:27)
  at io.healthgrades.dataload.evented.SnowpipeRestClient$.$anonfun$ingestResponse$5(SnowpipeRestClient.scala:77)
  ...
```

**Comment by sziegler** [comment]
This sounds like a bug.  We will look into this.  Which endpoint were you calling?

Just FYI the REST endpoints are simply including the requestId given by the REST request in the response for convenience.  While the Java API may use UUIDs, this is not required by the REST endpoint.  At  first glance, it appears that here the server is not echoing the requestId properly.

**Comment by ml10** [comment]
This was with the `/v1/data/pipes/{pipeline}/insertFiles` endpoint. 

I can see how the UUID isn't strictly needed, but as `net.snowflake.ingest.SimpleIngestManager` is now, if I don't provide one, the `SimpleIngestManager` generates one for me before sending the request.

**Comment by Hartland-3** [comment]
Has there been movement on this bug at all? Our implementation is using snow pipe to ingest a large number of files, and I'd like a way to get some kind of parseable confirmation that the API was successfully called.

**Comment by jaympatel-sf** [comment]
Hey there, I have seen the same issue with this, I will try to improve this. Looks like it is not unmarshalling the response received into IngestResponse.
