### ISSUE TITLE
SimpleIngestManager prevents safe shutdown of application

### ISSUE THREAD

**Issue by mjreiss** [snowflakedb/snowflake-ingest-java#15]
SimpleIngestManager uses RequestBuilder internally, which in turn uses a SecurityManager (all Snowflake SDK-built classes).

The SecurityManager initializes a static ScheduledExecutorService via Executors.newScheduledThreadPool. However this thread pool cannot be closed and has some arguably incorrect default properties set. Notably, it currently uses the default Executors.defaultThreadFactory() internally, which:

- makes threads with non-obvious names (e.g. 'pool-2-thread-1')
- makes non-daemon threads

The non-daemon threads results in an application that will not shut down, and there does not exist any .close or .shutdown method on SimpleIngestManager to allow an application manager to signal shutdown.

Suggestions:

- At a minimum, make the underlying thread pool use non-daemon threads
- Ideally, the thread pool would be non-static, and a shutdown mechanism would be added allowing an application developer to shut down any underlying thread pools and other dependencies the system introduced during normal execution.

**Comment by mjreiss** [comment]
Checking to see if this issue is being worked on, or if there is any timeline for when you think it might get resolved?

**Comment by varunganesh88** [comment]
Hi Mike, we should have this fixed by this week. Thanks for checking in.

**Comment by varunganesh88** [comment]
It should be fixed now.

**Comment by mjreiss** [comment]
@varunganesh88 Do you plan on doing a release that will include this fix? We would like to incorporate the SDK into our product without building the jar ourselves. Thanks!

**Comment by varunganesh88** [comment]
@mjreiss We will release this Thursday. Sorry for the delay. Thanks!

**Comment by varunganesh88** [comment]
@mjreiss The change had been released last Friday.
