### ISSUE TITLE
Sample project repository

### ISSUE THREAD

**Issue by stewartbryson** [snowflakedb/snowflake-ingest-java#152]
Is there a sample github repo using this library somewhere?

Thank you.

**Comment by sfc-gh-tzhang** [comment]
@stewartbryson yes, you could look at https://github.com/snowflakedb/snowflake-kafka-connector and see how `SimpleIngestManager` is used. Also you could look at [SnowflakeIngestBasicExample.java](https://github.com/snowflakedb/snowflake-ingest-java/blob/80f2cdc69fc458e32d2664448377b659daabacc4/src/main/java/net/snowflake/ingest/example/SnowflakeIngestBasicExample.java) for a very basic example.
