### ISSUE TITLE
Add ability to shut down individual SimpleIngestManagers

### ISSUE THREAD

**Issue by Daenyth** [snowflakedb/snowflake-ingest-java#20]
In my application I noticed there's no way for me to shut down individual ingest managers other than stopping the whole application. I'd prefer to close them, since they're not running 100% of the time, and I don't really have a way to control the total number of threads started due to the internal pool usage.

I'd like to only run them when I have work to do. If a close method (perhaps implementing `Autoclosable`?) were added, that would allow me to have the behavior I want.

**Comment by Hartland-3** [comment]
Is there any intention to resolve this? The assumption that this object should persist for the entire application runtime makes this library un-usable for applications that use many different Snowpipes.
