### ISSUE TITLE
Release notes for 0.9.5?

### ISSUE THREAD

**Issue by Daenyth** [snowflakedb/snowflake-ingest-java#33]
Maven central has a 0.9.5 release but it seems like the github repo here doesn't have the code for it. There's also no mention of anything newer than 0.9.1 on the release page

Further, `SimpleIngestManager` has a constructor marked `@Deprecated` with no note about why, what to use instead, or any mention of release notes or deprecation schedule.

Can the release notes as least be posted publicly, if the github repo isn't going to be kept up to date?

**Comment by howryu** [comment]
We have code in github but we just did not tag to the right commit with release number. We will try to tag them.
