### ISSUE TITLE
Getting 401 while running example

### ISSUE THREAD

**Issue by mevivs** [snowflakedb/snowflake-ingest-java#34]
I have downloaded https://github.com/snowflakedb/snowflake-ingest-java and setup with account credentials. While running SnowflakeIngestBasicExample i am getting,

[main] INFO net.snowflake.ingest.SimpleIngestManager - Attempting to unmarshall insert response - HttpResponseProxy{HTTP/1.1 401 Unauthorized [Content-Type: application/json, Date: Fri, 07 Jun 2019 14:41:07 GMT, Server: nginx, Content-Length: 124, Connection: keep-alive] ResponseEntityProxy{[Content-Type: application/json,Content-Length: 124,Chunked: false]}}

[main] WARN net.snowflake.ingest.connection.ServiceResponseHandler - Exceptional Status Code found in unmarshallInsert Response - 401

[main] ERROR net.snowflake.ingest.connection.ServiceResponseHandler - Status code 401 found in response from service

Service exception: 

HTTP Status: 401

{

Message: Incorrect username or password was specified.,

Data: null

}

**Comment by sfc-gh-japatel** [comment]
The error message is self explanatory. Feel free to reopen if not working anymore.
