### ISSUE TITLE
Snowflake JWT logging issue

### ISSUE THREAD

**Issue by islobodch** [snowflakedb/snowflake-ingest-java#47]
We are currently using [snowflake-kafka-connector](https://github.com/snowflakedb/snowflake-kafka-connector) to connect to Snowflake from Kafka. This solution relies on your this library (snowflake-ingest-java) to auth to snowflake. There is a bug in this library which logs the snowflake JWT (unsecure). We need a release of the library, to bump the dependency version in the connector and a release of the connector so that we can run a version without this bug.  We have previously [opened a PR](https://github.com/snowflakedb/snowflake-ingest-java/pull/45) and it has been merged.

**Comment by gjorgji** [comment]
We will be doing a new release very soon. CC: @howryu
