### ISSUE TITLE
Issues writing a List of JSON objects (Strings) to an Array while maintaining inner variant structure

### ISSUE THREAD

**Issue by joshtree41** [snowflakedb/snowflake-ingest-java#493]
Hi Team,

This is really an issue combined w/ a question. The General idea is that I'm having some trouble writing List<String> types to Array or Variant columns in Snowflake with the inner String element is a valid JSON string.

Here's a small example to get at what I'm referring to:

```java
List<MyType> myType = List.of(myType1, myType2);
List<String> myTypeString = myType.stream().map(<some GSON to write to string>).collect(Collectors.toList())
```

In the above example the `myTypeString` objects will be written to a Snowflake Array and Variant type like this:

```
[
  "{\"field1\":\"7831554\",\"field\":\"7831554\",\"field3\":5.0}"
]
```

I don't want the database users to have to call a `PARSE_JSON` on the contents of each element of the array. I was hoping that the escaped JSON string would be loaded into a nested VARIANT structure.

Is there any way (besides dumping the whole object to a JSON string) that I can get this desired output?

There are some limitations with the data structures that we're working with that make the above a much more attractive approach than dumping the `List<MyType>` to a JSON string.

**Comment by sfc-gh-lsembera** [comment]
Hi @joshtree41 , please serialize your type into a Map, not to a string. It will be ingested into Snowflake as variant, which you can directly query without calling `parse_json`.

Here is the list of accepted Java data types: https://docs.snowflake.com/user-guide/data-load-snowpipe-streaming-overview#supported-java-data-types

**Comment by joshtree41** [comment]
Hey @sfc-gh-lsembera, thank you! That makes sense to me ... but just to confirm, if I convert that column to:

```java
List<Map<String, Object>> arrayOfVariants ...
```

Assuming the the inner `Object` value is a supported data type, then I should be okay?

I should be able to test this out this week, I can follow up here with findings.

**Comment by sfc-gh-lsembera** [comment]
@joshtree41 Exactly, if the inner object is a supported semi-structured data type, e.g. another `Map`, `List` or a primitive data type, you will be ok. Please try it out and let us know your findings.

**Comment by sfc-gh-lsembera** [comment]
@joshtree41 Just make sure you are using a recent (non-beta) version of the SDK (1.1.1 or newer).

**Comment by joshtree41** [comment]
@sfc-gh-lsembera just tested w/ 1.1.3 and the `List<Map<String, Object>>` worked. Thanks for the help man! Going to close this issue now.
