### ISSUE TITLE
2.0.1-unshaded release

### ISSUE THREAD

**Issue by jdcaperon** [snowflakedb/snowflake-ingest-java#541]
Hi, would it be possible to trigger a release of the 2.0.1 unshaded dependency? Currently it doesn't seem like the unshaded dependency is being released on a regular cadence.

<img width="161" alt="image" src="https://github.com/snowflakedb/snowflake-ingest-java/assets/30421879/b31980ac-f0cf-47fd-9d8e-b363688d759f">

Can I recommend instead releasing the unshaded dependency as a different dependency in Maven? E.g. https://mvnrepository.com/artifact/com.google.javascript/closure-compiler-unshaded This would mean that dependency upgrade tools like Dependabot will continue to work, currently the versioning mechanism in use means that it isn't the case.

**Comment by sfc-gh-rcheng** [comment]
@jdcaperon we are planning on releasing an unshaded version eventually, however we have been busy with GA, so we may not be able to do it for a little bit. Thanks for the suggestion to release the unshaded version as a different dependency, we will do that for future unshaded releases.

I'll leave this issue open, and update/close it when we have a new unshaded version released

**Comment by jdcaperon** [comment]
Hi @sfc-gh-rcheng, looks like you've disabled old versions of the SDK from working but haven't released the unshaded 2.0.0 SDK, this is quite disappointing and not really adequate behaviour. Please release the `unshaded` 2.0.0 SDK so we can upgrade and continue developing with snowflake streaming.

**Comment by sfc-gh-tzhang** [comment]
2.0.2-unshaded should be released, do you want to give it a try?
