### ISSUE TITLE
Retrieve channel status for multiple channels

### ISSUE THREAD

**Issue by jdcaperon** [snowflakedb/snowflake-ingest-java#555]
Hello,

Would it be possible to create an interface to retrieve the channel status of many channels? Currently, for each channel I have open I have to make a separate request to SF for each channel status. Ideally I would make a single request that returns the channels status for all the channels I care about to avoid the overhead of making lots of requests.

https://github.com/snowflakedb/snowflake-ingest-java/blob/6e4eb63e56874f3bcea516894de7e0fb99392a58/src/main/java/net/snowflake/ingest/streaming/internal/SnowflakeStreamingIngestChannelInternal.java#L382-L401

Cheers

**Comment by sfc-gh-xhuang** [comment]
Hi @jdcaperon we do have a SQL command `[SHOW CHANNELS](https://docs.snowflake.com/en/sql-reference/sql/show-channels)` that currently shows the channel offset. 

Would adding a status to that command be sufficient?

**Comment by jdcaperon** [comment]
> Would adding a status to that command be sufficient?

Hmmmm, ideally I wouldn't have to open a JDBC client as well, but if thats the supported path I can do that however nasty it feels. Would it be possible to extend the Client interface to have support? AFAICT the machinery already exists to query the status of multiple channels from the client code since the client is querying a list of channels on shutdown.

```java
public interface SnowflakeStreamingIngestClient extends AutoCloseable {
...
  ChannelStatus getStatusForChannels(Collection<SnowflakeStreamingIngestChannel> channels);
...
}
```

**Comment by sfc-gh-tzhang** [comment]
Yes, we could take this as a small feature request, it should be fairly easy given that we already support it in the REST API

To be clear, we don't even expose the channel status for one channel, we just expose the offset token, basically what you want is a function under `SnowflakeStreamingIngestClient` to return a list of offset tokens?

**Comment by jdcaperon** [comment]
> To be clear, we don't even expose the channel status for one channel, we just expose the offset token, basically what you want is a function under SnowflakeStreamingIngestClient to return a list of offset tokens?

Yeah exactly. I was thinking it might be nice to have access to things like whether the channel `isValid` as well, but committed offset tokens is the hard requirement I need right now.

**Comment by sfc-gh-tzhang** [comment]
This is done, closing
