### ISSUE TITLE
Only flush channels for tables with a channel that needs flushing rather than flushing all channels for all tables

### ISSUE THREAD

**Issue by jdcaperon** [snowflakedb/snowflake-ingest-java#570]
DISCLAIMER: This is based on my interpretation of the SDK, still getting up to speed on the internals.

Currently the SDK attempts to flush all channels on an interval, instead, would it be possible and potentially more efficient to only flush channels where the rowbuffer has hit the expected size? In high volume/high channel count use cases the SDK has to flush a large number of blobs after every time period.

For example, if we have 100 channels, and a flush interval of 1 second where each channel receives at least 1 row per second. Then the SDK will attempt to flush 100 chunks every second. Even if the flush interval is increased to 60 seconds, if a single channel in our list of 100 channels needs flushing once per second because it is higher volume than remaining channels, then the SDK will still attempt to flush 100 chunks every second.

Instead, if the `FlushService` is refactored such that it knows which tables/channels need to be flushed then the number of chunks being pushed can be reduced. Taking the example above where there exist 100 channels, with a single channel needing to be flushed every second, with a force flush interval of 60 seconds. There should ideally be 1 chunks being pushed every second (assuming the rowbuffers stack to a single blob), rather than 100 chunks.

e2: Potentially there is scope to have the interval be per table so that regularly flushing tables don't need to be force flushed as part of the flush cycle which could potentially help with increasing size of the blobs being pushed, assuming that bigger blobs are better. This would also help avoiding the glut of requests/volume when flushing on the interval.

My understanding is that this should be okay, as ordering is only preserved within channels, so processing data out of order is okay across different tables.

I understand this might be a fairly big refactor of some of the SDK, would be keen to hear your thoughts or whether I am off track with my understanding of the code. I'm hoping this helps with some of the issues I've seen with high blob counts causing networking errors.

e: I'm also happy to provide an implementation/PR for this with guidance if this isn't going to be prioritized.

e3: Blob -> Chunk

**Comment by sfc-gh-lsembera** [comment]
Hi @jdcaperon, the SDK is flushing every second to keep the latency low. If there are 100 channels which have some data, the SDK needs to flush it, even if each channel has just one row.

**Comment by jdcaperon** [comment]
> the SDK is flushing every second to keep the latency low.

@sfc-gh-lsembera true, but this is also causing massive complexity in clients with a high table count, afaict there is no upper limit to the complexity of a blob which causes issues in the Snowflake Backend due to the latency associated with processing complex blobs. In fact, you get worse latency flushing every 1 second because the Register Blobs requests can't process complex blobs quick enough.

The client works really well in these arbitrarily simple use cases, but there isn't any restrictions in place to prevent complex clients blowing themselves up, as I've experienced quite regularly.

**Comment by sfc-gh-lsembera** [comment]
> > If there are 100 channels which have some data, the SDK needs to flush it, even if each channel has just one row.

> OOI Why is that? Why can't channels flush independently?

@jdcaperon Because we want to combine data from multiple channels for a single table into one chunk for efficiency.

We are aware that there are currently issues while ingesting into many tables from a single client and we are discussing possible solutions both in the client-side and server-side. One of them is limiting the number of chunks that can go into one blob, as well as limiting the number of blobs that can go into one blob registration request. Currently, the only workaround is to create multiple instances of `SnowflakeStreamingIngestClient` and use each one to ingest data into fewer tables.

**Comment by jdcaperon** [comment]
> Because we want to combine data from multiple channels for a single table into one chunk for efficiency.

@sfc-gh-lsembera Makes sense, would it be possible to flush channels for just that table then?

> We are aware that there are currently issues while ingesting into many tables from a single client and we are discussing possible solutions both in the client-side and server-side. One of them is limiting the number of chunks that can go into one blob, as well as limiting the number of blobs that can go into one blob registration request.

Understandable! I guess this is me thinking about how it can be done from the client side to limit the number of chunks per blob. The workload I have is unique in that there is only a single channel per table (to reduce the total channel count). I originally rolled this idea because I thought that having too many channels was a bad idea. But I see now that having more channels is not necessarily bad as long as they can be chunked together. If anything having more channels is better because rather than having a channel buffer becoming full quickly, if you spread the load out for a table across multiple channels, they don't need to be flushed as often and you have to push less blobs.

I think this is one of those interesting things about the design that isn't really apparent when integrating with the SDK. There is a lot of underlying complexity that is not apparrent when working with this SDK at scale. How channels are flushed, how they are chunked together, how complex the blobs are for chunking. It seems like there is potentially a lot of work that could be done into identifying the "optimal" way to implement this data solution at scale. Working with low data and table volumes means that there is none of the complexity and it all works smoothly.

**Comment by sfc-gh-lsembera** [comment]
> I guess this is me thinking about how it can be done from the client side to limit the number of chunks per blob.

In the current SDK version, there is no way to limit this. If you are ingesting into N tables (regardless via how many channels) with a single client, there can be up to N chunks in a blob.

> There is a lot of underlying complexity that is not apparrent when working with this SDK at scale. How channels are flushed, how they are chunked together, how complex the blobs are for chunking.

We will consider expanding our documentation with some of these implementation details.
