### ISSUE TITLE
Sequence/Ordering  

### ISSUE THREAD

**Issue by vsrinivasan08** [snowflakedb/snowflake-ingest-java#583]
Introducing a Delay in processing the loop/input stream, changes the order/sequencing of data storing at the snowflake table.

Delay introduced using sleep - **Thread.sleep(3000);**. Also changing the delay to 1s, 2s, 3s... changes the order each time.

**Will there be a guaranteed sequencing without `ORDER BY` in the query ?**

```
            SnowflakeStreamingIngestChannel channel1 = client.openChannel(request1);

            final int totalRowsInTable = 10;
            for (int val = 0; val < totalRowsInTable; val++) {
                Map<String, Object> row = new HashMap<>();

                // c1 corresponds to the column name in table
                row.put("c1", String.valueOf(val));
                // Insert the row with the current offset_token
                InsertValidationResponse response = channel1.insertRow(row, String.valueOf(val));
                if (response.hasErrors()) {
                    throw response.getInsertErrors().get(0).getException();
                }
                Thread.sleep(3000);                  // Delay in the input stream
            }
```
https://github.com/snowflakedb/snowflake-ingest-java/blob/257aeee14b5db20decf7eebf23f844432c348b83/src/main/java/net/snowflake/ingest/streaming/example/SnowflakeStreamingIngestExample.java#L63

`select c1 from MY_TABLE`  Supposed to be 0,1,2,3,4,5,6,7,8,9 but it is kind of in the different order, Also based on each delay order differs

![image](https://github.com/snowflakedb/snowflake-ingest-java/assets/113498972/14518507-7a53-4148-9998-fa84b34873ed)

**Comment by sfc-gh-lsembera** [comment]
There is no guaranteed ordering in queries without `ORDER BY`. Ordering guarantees provided by Snowpipe Streaming mean that if a certain channel offset is committed in the table, previous offsets in the channel are committed, as well. It does not mean that they would be returned in the same order in select queries without `ORDER BY`.

**Comment by sfc-gh-lsembera** [comment]
@vsrinivasan08 Can we close this issue?
