### ISSUE TITLE
About channel getting invalid

### ISSUE THREAD

**Issue by xuanziranhan** [snowflakedb/snowflake-ingest-java#585]
Hi friends,
Sorry for asking the question here, please point me to the right place if we know.

We are using the client library to write streaming data to snowflake in aws lambda, but kept getting
`net.snowflake.ingest.utils.SFException: Channel INGEST.TEST_SCHEMA.TEST_QUERY_LOGS.INGEST.TEST_SCHEMA.TEST_QUERY_LOGS is invalid and might contain uncommitted rows, please consider reopening the channel to restart.
	at net.snowflake.ingest.streaming.internal.SnowflakeStreamingIngestChannelInternal.checkValidation(SnowflakeStreamingIngestChannelInternal.java:462) ~[snowflake-ingest-sdk-2.0.2.jar:?]
	at net.snowflake.ingest.streaming.internal.SnowflakeStreamingIngestChannelInternal.close(SnowflakeStreamingIngestChannelInternal.java:273) ~[snowflake-ingest-sdk-2.0.2.jar:?]`

We tried to see when a channel could be invalidated, looks like we encounter registering blob failures quite often. Is this something expected, we just handle the error, or is there something we could do to reduce the chance of this error.

Thanks a lot!

**Comment by sfc-gh-xhuang** [comment]
Hi @xuanziranhan Do you have a support ticket open on this issue? We need a little bit more info to look into it.

**Comment by xuanziranhan** [comment]
> Hi @xuanziranhan Do you have a support ticket open on this issue? We need a little bit more info to look into it.

Hi @sfc-gh-xhuang , thanks for replying. I don't. Where should I create the support ticket?

**Comment by vsrinivasan08** [comment]
@xuanziranhan, I have faced this while testing in dev and staging often. Found my channel name was unique after reading the SDK Java doc. Generating a unique channel name resolved the issue (Something like appending timestamp at the end)

**Comment by xuanziranhan** [comment]
> @xuanziranhan, I have faced this while testing in dev and staging often. Found my channel name was unique after reading the SDK Java doc. Generating a unique channel name resolved the issue (Something like appending timestamp at the end)

We have unique channel names.
