### ISSUE TITLE
Possible weaknesses detected

### ISSUE THREAD

**Issue by lukasnow0** [snowflakedb/snowflake-ingest-java#598]
Hi,

We use snowflake-ingest-java:2.0.3 in our project and our Veracode scan detected possible weaknesses ranging from very high to medium severity: CWE-78, CWE-114, CWE-732, CWE-117, CWE-259, CWE-331, CWE-327, CWE-73, CWE-611, CWE-470,  CWE-377. According to the scan results all of the above are loaded with third-party libraries.

![image](https://github.com/snowflakedb/snowflake-ingest-java/assets/11982993/0dc7b5bf-7f12-4c5a-9cbe-0715191f85ea)
![image](https://github.com/snowflakedb/snowflake-ingest-java/assets/11982993/8f084e08-96a1-43f1-bc47-51f960168ceb)
![image](https://github.com/snowflakedb/snowflake-ingest-java/assets/11982993/237326b5-b0ad-47f7-92bd-bc8ac3018178)
![image](https://github.com/snowflakedb/snowflake-ingest-java/assets/11982993/97430ea0-d2cb-4ff2-ab63-27710e4a74c4)
![image](https://github.com/snowflakedb/snowflake-ingest-java/assets/11982993/c809420e-d913-49a4-9047-24060836b8dc)
![image](https://github.com/snowflakedb/snowflake-ingest-java/assets/11982993/736ded70-19ee-43a0-a5d2-5729e63d453a)
![image](https://github.com/snowflakedb/snowflake-ingest-java/assets/11982993/d5533142-579d-443e-97d9-5127f8a37abd)
![image](https://github.com/snowflakedb/snowflake-ingest-java/assets/11982993/ca7011c5-09e1-4413-b6d7-4b6d21c2d600)
![image](https://github.com/snowflakedb/snowflake-ingest-java/assets/11982993/859be17c-a5ac-4db8-9109-981805d890a3)
![image](https://github.com/snowflakedb/snowflake-ingest-java/assets/11982993/87ab1f14-a4ca-4d65-a065-277c854f8502)
![image](https://github.com/snowflakedb/snowflake-ingest-java/assets/11982993/ea24dbbe-9a70-43ec-adcb-07e2a761be63)

Please address these findings if possible.

**Comment by lukasnow0** [comment]
Thanks for the quick response!

 I will continue to use this SDK, that's for sure, but I just wanted to be on the safe side. I assume that most of the weaknesses reported by the Veracode scan are probably false positives or mitigated by design, especially knowing that other scans did show nothing. Please investigate it on your end and share the results.

**Comment by sfc-gh-xhuang** [comment]
Our snyk bot opens issue when it detects possible CVEs which we triage to fix assuming a fix is available. 

We have released 2.0.4 at the end of Oct, which fixed a few vulnerabilities by upgrading snappy-java, bc-fips, protobuf-java, etc as indicated in release notes.

We monitor and run vulnerability scans constantly and will address issues as they are raised.
