### ISSUE TITLE
NoSuchMethodError when using snowflake-ingest-sdk 2.0.3

### ISSUE THREAD

**Issue by sfc-gh-kterada** [snowflakedb/snowflake-ingest-java#599]
Sharing for awareness: https://github.com/snowflakedb/snowflake-jdbc/issues/1524

**Comment by sfc-gh-kterada** [comment]
Until there's a fix available, please use a [supported](https://github.com/snowflakedb/snowflake-ingest-java#dependencies) 3.13.x version of the Snowflake JDBC driver.

**Comment by sfc-gh-xhuang** [comment]
JDBC 3.14.3 was recently released and fixes this.

**Comment by sfc-gh-xhuang** [comment]
@sfc-gh-tzhang @sfc-gh-psaha Can you of you upgrade the dependency to JDBC 3.14.3 for the next release?

**Comment by sfc-gh-xhuang** [comment]
This has been resolved in the latest 2.1.0 sdk release as we have upgraded to JDBC 3.14.5
