### ISSUE TITLE
Is insertRows atomic?

### ISSUE THREAD

**Issue by koszti** [snowflakedb/snowflake-ingest-java#646]
It's more like a question rather than an issue. Is `insertRows` atomic?

Or in other words is it possible to insert two rows in one transaction? Let's say we have a logical group of two rows that we ingest by a  single `insertRows` command and we want to avoid that at any point of time and in case of any failure only one of them is selectable from the target table. Is that possible somehow?

**Comment by sfc-gh-lsembera** [comment]
Hi @koszti, `insertRows` is atomic, either the whole batch or nothing is committed. It is the consequence of the fact that offset tokens used to track ingestion progress are passed for the whole batch, not per individual rows.

However, rows can be missing if the channel is configured to use `OnErrorOption.CONTINUE`, in which case rows that fail validation would be omitted. When using `OnErrorOption.CONTINUE`, we recommend to always check the `InsertValidationResponse`.

**Comment by sfc-gh-lsembera** [comment]
Hi @koszti, can we close this issue?

**Comment by koszti** [comment]
yes we can. thanks for the answer
