### ISSUE TITLE
Bytes transferred out of application information

### ISSUE THREAD

**Issue by szkoludasebastian** [snowflakedb/snowflake-ingest-java#652]
Hi All!
It's rather question than issue. As a team, we use snowflake ingest sdk to upload our customers data to their snowflake tables. We use the Snowpipe Streaming functionality to do this. We need information about how many bytes are going out of our application. I found information in your code that you are sending data in blob form. Is there any way to extract information about the size of each blob being transferred? As you can see in the following screenshot you provide such informations in the logs.
<img width="1027" alt="blob_size_log" src="https://github.com/snowflakedb/snowflake-ingest-java/assets/141229367/8086d551-dfe3-41c7-874b-f3ac077c635f">
If there is currently no such possibility to extract such data, is there a chance to add it?

**Comment by sfc-gh-xhuang** [comment]
Hi @szkoludasebastian 
Our [client history view](https://docs.snowflake.com/en/sql-reference/account-usage/snowpipe_streaming_client_history) provides information at the client level the amount of bytes transferred to Snowflake. 

Is there something more that you would like to see?

**Comment by sfc-gh-xhuang** [comment]
Hi @szkoludasebastian Do you have any other feedback based on the previous response?
