### ISSUE TITLE
Unshaded version of 2.0.5 release was not published 

### ISSUE THREAD

**Issue by enzo-cappa** [snowflakedb/snowflake-ingest-java#685]
The unshaded version of 2.0.5 release was not published. This is specially problematic for FIPS environments, where the shaded version can not be used.

**Comment by sfc-gh-xhuang** [comment]
@enzo-cappa Would it be okay if we just release the now latest unshaded version of 2.1.0? 

cc: @sfc-gh-tzhang

**Comment by enzo-cappa** [comment]
It would work for me, as I changed the plans of what I want to do. I was planning to build https://github.com/snowflakedb/snowflake-kafka-connector with FIPS support, but it proven to be too difficult and risky.
However, I do see value of always releasing shaded and non-shaded versions.

**Comment by sfc-gh-xhuang** [comment]
2.1.0 has been released
