### ISSUE TITLE
Clarify JDBC driver version requirements

### ISSUE THREAD

**Issue by wesleyhillyext** [snowflakedb/snowflake-ingest-java#804]
The README.md currently states, under Dependencies:

> snowflake-jdbc (3.16.1+)

But under Prerequisites:

> **If your project depends on the Snowflake JDBC driver, as well, please make sure the JDBC driver version is 3.13.30 to 3.14.5.

Looking at the version history, I assume the former is correct and the latter is now out of date. Can you confirm that, and update the readme? Thanks!

**Comment by sfc-gh-xhuang** [comment]
Thanks for raising this! I have an update to the readme out to remove the Prerequisites section and note. 

It's recommended to use the latest JDBC version whenever possible.  3.16.1+ is best with the latest 3.18.0 being recommended for our next release
