### ISSUE TITLE
Building or uploading blob failed due to ingest client internal IO error or timeout

### ISSUE THREAD

**Issue by PatrykWitkowski** [snowflakedb/snowflake-ingest-java#806]
**The client version**: 2.0.3

**The problem description**:
We use snowflake ingest SDK to send data from our system to Snowflake. From time to time we're getting errors like below that come from internal SDK code - we cannot specify when it happens exactly, but we see it randomly on our production environments and it's causing that data is not delivered and lost.

![image](https://github.com/user-attachments/assets/dba1acf4-9744-4d5f-8881-ca4288af7c4d)
![image](https://github.com/user-attachments/assets/47e3448e-84ae-45df-8358-57a98f40a01c)

**Comment by PatrykWitkowski** [comment]
Also noticed the same error due to NPE in the telemetry service

![image](https://github.com/user-attachments/assets/af567b19-7188-4d6e-99b8-cd6d860584b2)

**Comment by sfc-gh-tzhang** [comment]
hi, 2.0.3 is a pretty old version and we have made various fixes in this area, I'm not sure about the IO issue but we definitely fixed the NPE issue, please upgrade to the latest SDK version and report back if you still see this issue, thanks!
