### ISSUE TITLE
v2.2.2-unshaded release

### ISSUE THREAD

**Issue by wesleyhillyext** [snowflakedb/snowflake-ingest-java#844]
Hi, we received communication INC0113642 advising us to upgrade to v2.2.2 to avoid a duplicate row ID bug in our use of Snowpipe Streaming.

We use the unshaded version of this library, but the latest version with an unshaded release appears to be just v2.2.0. Can you release v2.2.2-unshaded? In general, is there a reason the unshaded release lags behind or is skips certain versions entirely?

(I'm looking at https://mvnrepository.com/artifact/net.snowflake/snowflake-ingest-sdk but let me know if that's the wrong place to look).

Thanks,
Wesley

**Comment by sfc-gh-xhuang** [comment]
We will be releasing 2.3.0 shaded and unshaded versions next week

**Comment by sfc-gh-tzhang** [comment]
2.2.2-unshaded has been released, please give it a try and let us know if there is any issue, thanks!
