### ISSUE TITLE
[Snowpipe Streaming] Question on Client-side encryption and CVE

### ISSUE THREAD

**Issue by tlopesPT** [snowflakedb/snowflake-ingest-java#899]
While trying to understand the impact of this [CVE](https://github.com/snowflakedb/snowflake-jdbc/security/advisories/GHSA-f686-hw9c-xw9c), I had a look at client-side encryption while using Snowpipe Streaming, but could not figure out if it's actually used (on any cloud provider).

According to [Understanding end-to-end encryption in Snowflake](https://docs.snowflake.com/en/user-guide/security-encryption-end-to-end): 

> 1. A user uploads one or more data files to a stage.
> If the stage is an internal (i.e. Snowflake) stage (Image B) data files are automatically encrypted by the Snowflake client on the user’s local machine prior to being transmitted to the internal stage

My understanding is that Snowpipe Streaming relies on internal stages, so I'd expect the above to be applicable.

> Client-side encryption follows a specific protocol defined by the cloud storage service. 

We have no control over which cloud provider is used, since we load data onto customers accounts.

> The customer creates a secret [master key](https://csrc.nist.gov/glossary/term/master_key), which is shared with Snowflake.

Is this possible or required for internal stages? Or can we rely on [Snowflake-managed keys](https://docs.snowflake.com/en/user-guide/security-encryption-manage#snowflake-managed-keys)?

And from [Snowpipe Streaming limitations](https://docs.snowflake.com/en/user-guide/data-load-snowpipe-streaming-overview#limitations):
> Snowpipe Streaming only supports using 256-bit AES keys for data encryption.

So I had a look at the "[incorrect key size condition check](https://github.com/snowflakedb/snowflake-jdbc/pull/1946/files)" and found that on both **SnowflakeAzureClient** and **SnowflakeGCSClient** `isClientSideEncrypted=true` but `encryptionKeySize=0`, meaning that this condition check is skipped.

Considering the above, we conclude that Snowpipe Streaming users are not affected by this CVE, correct?
Is Client-side encryption applied at a previous layer for internal stages? Or do we need any additional setup to enable it?

I appreciate any clarification.
Thanks,
Tiago

**Comment by sfc-gh-xhuang** [comment]
This CVE does not affect Snowpipe Streaming uploads
We have updated the snowflake-jdbc version anyway though
